### ISSUE TITLE
POST - Create user - Password validation [UX]

### ISSUE THREAD

**Issue by GCsabi** [teamcodeyard/tir-api#2]
**Steps to reproduce the issue:**

1.     Local dev environment must be running
2.     From Postman send the following request to the given endpoint (password doesn't contain special character)

```
 {
    "email": "trololololollolololooo@test.hu",
    "password": "helloworlD1"
} 
```  

**Expected Result:**
    "message": "The password must have minimum 1 special character"
    We would expect a helping hint for the user what is missing from a proper password, so that it wouldn't cause frustration.

**Actual Result:**
    "message": "The password must be at least 10 characters, must contain numeric characters, minimum 1 uppercase letter [A-Z] and minimum 1 special character"

**Comment by GCsabi** [comment]
**Steps to reproduce the issue:**

1.     Local dev environment must be running
2.     From Postman send the following request to the given endpoint (password doesn't contain special character)

```
 {
    "email": "trololololollolololooo@test.hu",
    "password": "helloworl1."
} 
```

**Expected Result:**
"message": "The password must have minimum 1 uppercase letter [A-Z]"
We would expect a helping hint for the user what is missing from a proper password, so that it wouldn't cause frustration.

**Actual Result:**
"message": "The password must be at least 10 characters, must contain numeric characters, minimum 1 uppercase letter [A-Z] and minimum 1 special character"

**Comment by GCsabi** [comment]
**Steps to reproduce the issue:**

1.     Local dev environment must be running
2.     From Postman send the following request to the given endpoint (password doesn't contain special character)

```
 {
    "email": "trololololollolololooo@test.hu",
    "password": "helloworlD."
} 
```

Expected Result:
"message": "The password must contain numeric characters"
We would expect a helping hint for the user what is missing from a proper password, so that it wouldn't cause frustration.

Actual Result:
"message": "The password must be at least 10 characters, must contain numeric characters, minimum 1 uppercase letter [A-Z] and minimum 1 special character"

**Comment by GCsabi** [comment]
**Steps to reproduce the issue:**

1.     Local dev environment must be running
2.     From Postman send the following request to the given endpoint (password doesn't contain special character)

```
 {
    "email": "trololololollolololooo@test.hu",
    "password": "hellow1D."
} 
```

Expected Result:
"message": "The password must be at least 10 characters,"
We would expect a helping hint for the user what is missing from a proper password, so that it wouldn't cause frustration.

Actual Result:
"message": "The password must be at least 10 characters, must contain numeric characters, minimum 1 uppercase letter [A-Z] and minimum 1 special character"

**Comment by GCsabi** [comment]
Could you please post an example of an actual 422 Error related Request?

**Comment by GCsabi** [comment]
**Steps to reproduce the issue:**

1.     Local dev environment must be running
2.     From Postman send the following request to the given endpoint (password doesn't contain special character)

```
{
    "email": "trololololollolololooo@test.hu",
    "password": "HELLOWORLlD.."
} 
```

**Expected Result:**
"message": "The password must contain minimum 1 lowercase letter [A-Z] "
We would expect a helping hint for the user what is missing from a proper password, so that it wouldn't cause frustration.

**Actual Result:**
"message": "The password must be at least 10 characters, must contain numeric characters, minimum 1 uppercase letter [A-Z] and minimum 1 special character"

**Comment by iujlaki** [comment]
Nice catch but it's out of scope right now.
