### ISSUE TITLE
POST - Create user - Handling +01 in email addresses

### ISSUE THREAD

**Issue by GCsabi** [teamcodeyard/tir-api#3]
**Steps to reproduce the issue:**

1. Local dev environment must be running
2. From Postman send the following request to the given endpoint (password doesn't contain special character)

```
{
    "email": "trolol+01@test.hu",
    "password": "helloworlD1."
}
```

**Expected Result:**
Successful registration

**Actual Result:**
  "message": "Invalid e-mail address"

**Comment by iujlaki** [comment]
We'd like to deny registrate with the same email address using + sign, so it's a valid scenario
